# Generated by Django 3.0.5 on 2020-04-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
    ]
